version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ml:
    build:
      context: .
      dockerfile: Dockerfile.ml
    container_name: ml
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8001:8001"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    depends_on:
      - db
      - ml
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    volumes:
      - .:/app

volumes:
  pgdata:
