"""add source and strategy columns

Revision ID: 3aa4ad0f41f6
Revises: 15511cb69ab1
Create Date: 2025-07-31 01:04:37.959343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa4ad0f41f6'
down_revision: Union[str, None] = '15511cb69ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('signal', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candles_date', 'candles', ['date'], unique=False)
    op.create_index(op.f('ix_candles_interval'), 'candles', ['interval'], unique=False)
    op.create_index('ix_candles_ticker', 'candles', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candles_ticker', table_name='candles')
    op.drop_index(op.f('ix_candles_interval'), table_name='candles')
    op.drop_index('ix_candles_date', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
