"""init schema

Revision ID: 51c9b2c0b52b
Revises: 
Create Date: 2025-07-27 14:00:07.695986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c9b2c0b52b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'interval', 'ts', name='uq_candle_ticker_interval_ts')
    )
    op.create_index(op.f('ix_candle_interval'), 'candle', ['interval'], unique=False)
    op.create_index(op.f('ix_candle_ticker'), 'candle', ['ticker'], unique=False)
    op.create_index(op.f('ix_candle_ts'), 'candle', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candle_ts'), table_name='candle')
    op.drop_index(op.f('ix_candle_ticker'), table_name='candle')
    op.drop_index(op.f('ix_candle_interval'), table_name='candle')
    op.drop_table('candle')
    # ### end Alembic commands ###
