"""update candles table for AI/stacking

Revision ID: c351c8a7490b
Revises: 3aa4ad0f41f6
Create Date: 2025-07-31 01:17:03.107469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c351c8a7490b'
down_revision: Union[str, None] = '3aa4ad0f41f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('candles', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('candles', sa.Column('is_latest', sa.Boolean(), nullable=True))
    op.drop_index('ix_candles_date', table_name='candles')
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_index('ix_ticker_interval_time', 'candles', ['ticker', 'interval', 'timestamp'], unique=False)
    op.drop_column('candles', 'created_at')
    op.drop_column('candles', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candles', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('candles', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('ix_ticker_interval_time', table_name='candles')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.create_index('ix_candles_date', 'candles', ['date'], unique=False)
    op.drop_column('candles', 'is_latest')
    op.drop_column('candles', 'meta')
    op.drop_column('candles', 'timestamp')
    # ### end Alembic commands ###
