# config/config.yaml
project:
  name: ml-trading-bot
  timezone: "Europe/Warsaw"

data:
  tickers: ["AAPL", "MSFT", "TSLA"]
  intervals: ["1h", "1d", "1wk"]
  raw_data_dir: "data-pipelines/feature_stores/data/raw"
  processed_data_dir: "data-pipelines/feature_stores/data/processed"

paths:
  feature_stores_processed: "data-pipelines/feature_stores/data/processed"
  results: "data-pipelines/feature_stores/data/results"

backtest:
  initial_cash: 100000
  strategies:
    - macd
    - rsi
    - sma
    - ema
    - bollinger

scoring:
  top_n: 20
  metric: "sharpe"   # możesz zmienić np. na: sortino, mar, cagr (pamiętaj żeby kolumna istniała)
  direction: "desc"  # "desc" dla metryk gdzie więcej = lepiej (Sharpe, CAGR, Sortino, MAR)