# config/config.yaml
defaults:
  - db: postgres

# ogólne ustawienia projektu
project:
  name: ml-trading-bot
  timezone: "Europe/Warsaw"

data:
  tickers: ["AAPL", "MSFT", "TSLA"]
  intervals: ["1h", "1d", "1wk"]
  start_date: "2018-01-01"
  end_date: "2024-12-31"

features:
  technical: true
  fundamental: false
  sentiment: false

paths:
  feature_store_processed: "data-pipelines/feature_store/data/processed"
  results: "data-pipelines/feature_store/data/results"

backtest:
  initial_cash: 10000.0
  strategies:
    - macd
    - rsi
    - sma
    - ema
    - bollinger